repeats: /Users/madileask/MSI_NGS/PROMIS/database/RMH200_v2_panel_cram_msi_loci.csv
output_dir: /Users/madileask/MSI_NGS/output/promis_output
scripts_dir: scripts/
msi_deviation: 0.1
cytoband: database/cytoBand_hg19.txt
# Minimum deduplicated reads per locus during extraction
min_reads: 5
# Minimum deviating reads to call instability
min_dev_reads: 5
# BAM filtering thresholds
bq_threshold: 20
mq_threshold: 40
# How to evaluate instability (count, percent, or both)
call_by: both
# Deviating-read percentage threshold
min_dev_percent: 10.0
# Minimum reference length percentage required for one 
min_length_percent: 20.0
# Use Gaussian Mixture Model to infer stable length
use_GMM: true
# Allowed imbalance for a second GMM component
balance_tolerance: 0.05
# Minimum total reads per locus required for scoring
min_total_reads: 50

#Set the input dir where the bam files are located
input_dir: /Users/madileask/MSI_NGS/input/BCI_Feb2025/sorted_bam
